general:
  seed: 999
  wandb: false
  num_classes: 135
  emb_dim: 512

wandb:
  project: arcface
  name: irsenet
  tags: ['irsenet', 'arcface']
  credentials: "wandb.env" # intialize credentials in this file
  save_dir: /workspace/SurveillanceAI/src/arcface/logs
  registry:
  - name: "face"

model:
  type: irsenet
  irsenet:
    input_size: 112
    backbone_path: /workspace/SurveillanceAI/src/arcface/weights/irsenet
    pretrained: false
    lr : 0.0001
  

loss:
  type: arcface
  arcface:
    s: 64.0  # scale
    m1: 1   # margin
    m2: 0.5
    m3: 0.35

data:
  path: /workspace/SurveillanceAI/src/arcface/data/faces
  input_size: 112
  use_dali: false # need to be done
  train_val_split: 0.85
  dataloader:
    batch_size: 32
    num_workers: 4

train:
  callbacks:
    early_stopping:
      patience: 1
      monitor: val_loss
      mode: min
    model_checkpoint:
      monitor: val_loss
      mode: min
      save_top_k: 1
      save_weights_only: true
      filename: '{epoch:02d}-{val_loss:.2f}'
    model_pruning:  # [need to implement - Error : while loading checkpoint]
      pruning_fn: 'l1_unstructured'
      amount: 0.2

  args:
    accelerator: gpu
    strategy: auto
    fast_dev_run: false
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 10
    enable_progress_bar: true
    default_root_dir: /workspace/SurveillanceAI/src/arcface/logs
    max_epochs: 100
    min_epochs: 1
    precision: 16-mixed
    accumulate_grad_batches: 1

train_pipeline:
  optimization: false
  post_training: true
  push_registry: false
  device: cuda
  model_path: /workspace/SurveillanceAI/src/arcface/weights/irsenet
  payload_map: /workspace/SurveillanceAI/src/arcface/data/label_map.csv
  compile_bs: 32 # batch size for compilation
  upload_size: 1000 # number of vectors to upload at once


inference_pipeline:
  ckpt_path: /workspace/SurveillanceAI/src/arcface/weights/irsenet.pt
  device: cuda

vector-db:
  db: "qdrant"
  dim: 512
  collection_name: "faces"
  credentials: "vectordb.env" # intialize credentials in this file
  quantization: false #"int8" # supported = ['int8']
  